name: CI - Build & SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para mejor análisis en SonarCloud

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:5.2.0.4988:sonar \
          -Dsonar.projectKey=Brandon-TG_Perruqueria_Github \
          -Dsonar.organization=brandon-tg \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.token=${SONAR_TOKEN} \
          -Dsonar.exclusions=src/test/java/** \
          -Dsonar.test.inclusions=src/test/java/** \
          -DskipTests







